/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as UUsernameSlugRouteImport } from './routes/u.$username.$slug'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameSlugRoute = UUsernameSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UUsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try': typeof TryRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/$slug': typeof UUsernameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try': typeof TryRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/$slug': typeof UUsernameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try': typeof TryRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/u/$username/$slug': typeof UUsernameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developers'
    | '/sitemap.xml'
    | '/try'
    | '/u/$username'
    | '/u/$username/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developers'
    | '/sitemap.xml'
    | '/try'
    | '/u/$username'
    | '/u/$username/$slug'
  id:
    | '__root__'
    | '/'
    | '/developers'
    | '/sitemap.xml'
    | '/try'
    | '/u/$username'
    | '/u/$username/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopersRoute: typeof DevelopersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TryRoute: typeof TryRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/$slug': {
      id: '/u/$username/$slug'
      path: '/$slug'
      fullPath: '/u/$username/$slug'
      preLoaderRoute: typeof UUsernameSlugRouteImport
      parentRoute: typeof UUsernameRoute
    }
  }
}

interface UUsernameRouteChildren {
  UUsernameSlugRoute: typeof UUsernameSlugRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameSlugRoute: UUsernameSlugRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopersRoute: DevelopersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TryRoute: TryRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
